package com.flight.ticketsAnalysis.entity;

public class CityRankEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -3502795160325973549L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** crId */
    private Integer cr_id;

    /** cityName */
    private String city_name;

    /** province */
    private String province;

    /** flightNumber */
    private Integer flight_number;

    public Integer getCr_id() {
        return cr_id;
    }

    public void setCr_id(Integer cr_id) {
        this.cr_id = cr_id;
    }

    public String getCity_name() {
        return city_name;
    }

    public void setCity_name(String city_name) {
        this.city_name = city_name;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public Integer getFlight_number() {
        return flight_number;
    }

    public void setFlight_number(Integer flight_number) {
        this.flight_number = flight_number;
    }
}