package com.flight.ticketsAnalysis.entity;

import java.math.BigDecimal;


public class CityEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 480380658862060971L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** cityId */
    private Integer city_id;

    /** cityName */
    private String city_name;

    /** province */
    private String province;

    /** cityX */
    private BigDecimal city_x;

    /** cityY */
    private BigDecimal city_y;

    public Integer getCity_id() {
        return city_id;
    }

    public void setCity_id(Integer city_id) {
        this.city_id = city_id;
    }

    public String getCity_name() {
        return city_name;
    }

    public void setCity_name(String city_name) {
        this.city_name = city_name;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public BigDecimal getCity_x() {
        return city_x;
    }

    public void setCity_x(BigDecimal city_x) {
        this.city_x = city_x;
    }

    public BigDecimal getCity_y() {
        return city_y;
    }

    public void setCity_y(BigDecimal city_y) {
        this.city_y = city_y;
    }
}