package com.flight.ticketsAnalysis.entity;/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.0.0
 */
/**
 * USER
 * 
 * @author bianj
 * @version 1.0.0 2019-08-09
 */
public class UserEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -5101039105500902540L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** userId */
    private Integer userId;

    /** username */
    private String username;

    /** password */
    private String password;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取userId
     * 
     * @return userId
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * 设置userId
     * 
     * @param userId
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * 获取username
     * 
     * @return username
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * 设置username
     * 
     * @param username
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * 获取password
     * 
     * @return password
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * 设置password
     * 
     * @param password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}